# Generated by Django 4.2.3 on 2023-07-21 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ibiteramo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ahobizobera', models.CharField(max_length=15)),
                ('debut', models.TimeField(max_length=15)),
                ('fin', models.TimeField(max_length=15)),
                ('ibeyi', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Itike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ibiteramo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ibiteramo.ibiteramo')),
                ('uwayimuhaye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itike',
            },
        ),
    ]
